---
downloads: ~/.ansible-downloads/

configure_sudoers: no
configure_terminal: no
configure_osx: no

dotfiles_repo: https://github.com/unn/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitconfig
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  - ack
  - adr-tools
  - awscli
  - autoconf
  - bash-completion
  - curl
  - ddev
  - direnv
  - doitlive
  - fish
  - gettext
  - gist
  - git
  - go
  - gpg
  - gpg2
  - jid
  - jq
  - hub
  - httpie
  - kubernetes-cli
  - kubernetes-helm
  - pandoc
  - tree
  - starship
  - sqlite
  - ssh-copy-id
  - readline
  - rvm
  - openssl
  - python-yq
  - pv
  - vscodium
  - watch
  - wget
  - wireguard-tools
  - zsh


### GitLab prereqs
  - redis
  - postgresql@9.6
  - libiconv
  - icu4c
  - cmake
  - node
  - npm
  - yarn
  - coreutils
  - re2

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - caskroom/drivers
  - caskroom/versions
  - drud/ddev

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - alfred
  - android-file-transfer
  - android-sdk
  - appzapper
  - atom
  - audio-hijack
  - authy
  - backblaze
  - balenaetcher
  - bartender
  - brave
  - caffeine
  - carbon-copy-cloner
  - choosy
  - colloquy
  - cyberduck
  - dash
  - docker
  - dropbox
  - firefox
  - garmin-express
  - garmin-virb-edit
  - gitter
  - google-chrome
  - gpg-suite
  - grandperspective
  - handbrake
  - hazel
  - iterm2
  - java
  - kitematic
  - lg-onscreen-control
  - little-snitch
  - macupdater
  - mamp
  - minikube
  - moom
  - nordvpn
  - notion
  - nvalt
  - phpstorm
  - sequel-pro
  - skype
  - slack
  - slingplayer-desktop
  - spectacle
  - spotify
  - suspicious-package
  - the-unarchiver
  - tunnelblick
  - vagrant
  - veracrypt
  - virtualbox
  - vlc
  - vscodium
  - vuescan
  - zoomus

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 937984704, name: "Amphetamine" }
  - { id: 979047768, name: "Browserism" }
  - { id: 671736912, name: "FruitJuice" }
  - { id: 540348655, name: "Monosnap" }
  - { id: 1384080005, name: "Tweetbot 3" }
  - { id: 1451685025, name: "WireGuard" }
